### ISSUE TITLE
Baseline Grid

### ISSUE THREAD

**Issue by CCucalonUTA** [emilyphayden/CTEC3350#3]
Hi Emily,

The Baseline Grid doesn't seem to be working just yet. 

I created a video tutorial to help you with it. https://enlightenment.design/baseline-grid/

If you have any questions feel free to reach out during or after class.

Thank you!

**Comment by CCucalonUTA** [comment]
On the Baseline Grid I noticed that the paragraphs are aligning well, however, the Headings are not.

Please take a look at those.

Thank you,

Carlos

**Comment by CCucalonUTA** [comment]
The assignment is almost complete.

Once you start going to a responsive size for each one of the media queries you should edit the baseline grid so that it can change alongside the text.

Good job!

Carlos

**Comment by emilyphayden** [comment]
I have now updated the Baseline Grid to be a working file
