### ISSUE TITLE
Flexbox assignment

### ISSUE THREAD

**Issue by CCucalonUTA** [emilyphayden/CTEC3350#4]
This assignment is incomplete.

Please follow the rubric.

If you have any questions feel free to reach out.

Thank you,

Carlos

**Comment by CCucalonUTA** [comment]
This assignment is late and can receive up to an 80 if turned in this evening.

**Comment by emilyphayden** [comment]
Finished and Fixed this assignment! Thank you for all of the help!

**Comment by CCucalonUTA** [comment]
Awesome! I'm glad I could help! :)
