### ISSUE TITLE
Form Assignment

### ISSUE THREAD

**Issue by CCucalonUTA** [emilyphayden/CTEC3350#5]
Please use flexbox to set up the layout on your form.
Also please use the CSS Selectors we learned on Tuesday to add more styles to the form.

**Comment by emilyphayden** [comment]
Fixed assignment and added flexbox and css selectors

**Comment by CCucalonUTA** [comment]
* The labels for the input fields are not working properly still. Please check out the slides to review how to add labels for the form to work properly when clicking on a label.
* The select field font is smaller than the rest of the fields.
* I also noticed that you are missing the submit button.
